name: "Restore Workspace"
description: "Setup Node/pnpm and restore build cache (requires checkout first)"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 9.0.0

    - name: Setup Node.js environment
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - name: Restore build artifacts
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          .turbo
          node_modules
          packages/*/dist
          packages/*/node_modules
          apps/*/node_modules
          apps/*/dist
          pnpm-lock.yaml
        key: build-${{ github.sha }}
        fail-on-cache-miss: true
